name: firebase_admin_interop
description: Firebase Admin SDK for Dart written as a wrapper around official Node.js SDK.
version: 2.1.0
homepage: https://github.com/pulyaevskiy/firebase-admin-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
publish_to: none

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  js: 0.6.2
  node_interop:
    git:
      url: git://github.com/Semapl3/node-interop
      path: node_interop
  meta: 1.2.3
  quiver_hashcode: ^2.0.0

dev_dependencies:
  build_runner: 1.11.1
  build_node_compilers:
    git:
      url: git://github.com/Semapl3/node-interop
      path: build_node_compilers
  test: ^1.15.7
  build_test: ^1.3.6